const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Behaviors.Tween,
		C3.Behaviors.skymenTrail,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.ScriptsInEvents.GameSheet_Event239_Act2,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Type: 0},
	{Destroy: 0},
	{WasOnTheScreen: 0},
	{Counter: 0},
	{Bomb: 0},
	{Dark: 0},
	{Egg: 0},
	{Hazelnut: 0},
	{Ice: 0},
	{Red: 0},
	{left: 0},
	{right: 0},
	{BigChocolate: 0},
	{itemUI: 0},
	{LOGO: 0},
	{BG: 0},
	{Table: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{JSON: 0},
	{Tween: 0},
	{imgPocket: 0},
	{TrailRenderer: 0},
	{Milk: 0},
	{Doubled: 0},
	{Pocket: 0},
	{Splash: 0},
	{DragDrop: 0},
	{TrailHead: 0},
	{SnowParticle: 0},
	{Sine: 0},
	{Snow: 0},
	{x2: 0},
	{txtAddTime: 0},
	{txtBigChocolate: 0},
	{txtPoint: 0},
	{Freeze: 0},
	{txtTimer: 0},
	{type: 0},
	{txtEnd: 0},
	{Character: 0},
	{num: 0},
	{Speech: 0},
	{txtSpeech: 0},
	{TutIcon: 0},
	{Popup: 0},
	{btn: 0},
	{Hand: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Clock: 0},
	{txtSISI: 0},
	{FrozenClock: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Chocolate: 0},
	{Button: 0},
	{Play: 0},
	{TimerEnable: 0},
	{End: 0},
	{Point: 0},
	{Timer: 0},
	{CreateChocTime: 0},
	{ChocolateFrames: 0},
	{ChocolateSpeed: 0},
	{ChocolateDestroyTime: 0},
	{gravity: 0},
	{DoublePointTimer: 0},
	{FreezeTimer: 0},
	{TutorialNum: 0},
	{MaxTutorial: 0},
	{TutorialEnable: 0},
	{HadTutorial: 0},
	{BigFellaCount: 0},
	{Life: 0},
	{left_start: 0},
	{left_end: 0},
	{right_start: 0},
	{right_end: 0},
	{x: 0},
	{y: 0},
	{dir: 0},
	{CUID: 0},
	{minus_one: 0},
	{chance: 0},
	{direction: 0},
	{frame: 0},
	{wait_time: 0},
	{tween_time: 0},
	{xx: 0},
	{yy: 0},
	{name: 0},
	{vValue: 0}
];

self.InstanceType = {
	Bomb: class extends self.ISpriteInstance {},
	Dark: class extends self.ISpriteInstance {},
	Egg: class extends self.ISpriteInstance {},
	Hazelnut: class extends self.ISpriteInstance {},
	Ice: class extends self.ISpriteInstance {},
	Red: class extends self.ISpriteInstance {},
	BigChocolate: class extends self.ISpriteInstance {},
	itemUI: class extends self.ISpriteInstance {},
	LOGO: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	imgPocket: class extends self.ISpriteInstance {},
	Milk: class extends self.ISpriteInstance {},
	Pocket: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	TrailHead: class extends self.ISpriteInstance {},
	SnowParticle: class extends self.IParticlesInstance {},
	Snow: class extends self.ISpriteInstance {},
	x2: class extends self.ISpriteInstance {},
	txtAddTime: class extends self.ITextInstance {},
	txtBigChocolate: class extends self.ITextInstance {},
	txtPoint: class extends self.ITextInstance {},
	txtTimer: class extends self.ITextInstance {},
	txtEnd: class extends self.ITextInstance {},
	Character: class extends self.ISpriteInstance {},
	Speech: class extends self.ISpriteInstance {},
	txtSpeech: class extends self.ITextInstance {},
	TutIcon: class extends self.ISpriteInstance {},
	Popup: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	txtSISI: class extends self.ITextInstance {},
	FrozenClock: class extends self.ISpriteInstance {},
	Chocolate: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {}
}